Update to add tar safe_extract
microsoft/DeepSpeed pull request #4279
Opened 2023-09-06 19:14 UTC by loadams

2023-09-06 21:10 UTC, loadams commented
@jeffra and @mrwyattii - the CVE in the linked PR would be more impactful if the tar files weren't just for our unit tests, so curious if we want to merge this change or not.

2023-09-11 17:06 UTC, mrwyattii approved these changes

2023-09-12 15:38 UTC, mrwyattii requested changes

2023-09-12 15:38 UTC, mrwyattii commented on tests/unit/modeling.py
Most of the code in this file and `modelingpreln` are completely unused. Let's remove unused code (including the `safe_extract`)

2023-09-14 21:38 UTC, closed without merging